# Generated by Django 2.1.5 on 2020-02-25 23:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experimenter', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Demsurv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(max_length=128)),
                ('age', models.CharField(max_length=128)),
                ('language', models.CharField(max_length=128)),
                ('country', models.CharField(max_length=128)),
                ('education', models.CharField(max_length=128)),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidexpr', models.ManyToManyField(blank=True, related_name='bidexpr', to='experimenter.Experiment')),
                ('currentexpr', models.ManyToManyField(blank=True, related_name='currentexpr', to='experimenter.Experiment')),
                ('pastexpr', models.ManyToManyField(blank=True, related_name='pastexpr', to='experimenter.Experiment')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
