# Generated by Django 2.1.5 on 2020-03-29 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('experimenter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demsurv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Others')], max_length=128)),
                ('age', models.IntegerField(choices=[(17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24'), (25, '25'), (26, '26'), (27, '27'), (28, '28'), (29, '29'), (30, '30')], default=0)),
                ('language', models.CharField(choices=[('English', 'English'), ('French', 'French'), ('German', 'German'), ('Korean', 'Korean')], max_length=128)),
                ('country', models.CharField(choices=[('UK', 'UK'), ('EU', 'EU'), ('Others', 'Others')], max_length=128)),
                ('education', models.CharField(choices=[('None', 'None'), ('School', 'School'), ('College', 'College'), ('Undergraduate', 'Undergraduate'), ('Postgraduate', 'Postgraduate')], max_length=128)),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifications', models.IntegerField(default=0)),
                ('decline', models.IntegerField(default=0)),
                ('bidexpr', models.ManyToManyField(blank=True, related_name='bidexpr', to='experimenter.Experiment')),
                ('currentexpr', models.ManyToManyField(blank=True, related_name='currentexpr', to='experimenter.Experiment')),
                ('decexpr', models.ManyToManyField(blank=True, related_name='decexpr', to='experimenter.Experiment')),
                ('pastexpr', models.ManyToManyField(blank=True, related_name='pastexpr', to='experimenter.Experiment')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
