# Generated by Django 2.1.5 on 2020-03-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demsurv',
            name='age',
            field=models.CharField(choices=[('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30')], max_length=128),
        ),
        migrations.AlterField(
            model_name='demsurv',
            name='country',
            field=models.CharField(choices=[('uk', 'UK'), ('eu', 'EU'), ('others', 'Others')], max_length=128),
        ),
        migrations.AlterField(
            model_name='demsurv',
            name='education',
            field=models.CharField(choices=[('s', 'School'), ('c', 'College'), ('u', 'Undergraduate'), ('p', 'Postgraduate')], max_length=128),
        ),
        migrations.AlterField(
            model_name='demsurv',
            name='language',
            field=models.CharField(choices=[('E', 'English'), ('F', 'French'), ('G', 'German'), ('K', 'Korean')], max_length=128),
        ),
        migrations.AlterField(
            model_name='demsurv',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Others')], max_length=128),
        ),
    ]
