# Generated by Django 2.1.5 on 2020-03-22 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20200322_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='notifications',
            field=models.IntegerField(default=0),
        ),
    ]
