# Generated by Django 2.1.5 on 2020-03-22 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_studentinfo_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='decline',
            field=models.IntegerField(default=0),
        ),
    ]
