# Generated by Django 2.1.5 on 2020-03-22 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experimenter', '0008_auto_20200322_1931'),
        ('student', '0007_studentinfo_decline'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='decexpr',
            field=models.ManyToManyField(blank=True, related_name='decexpr', to='experimenter.Experiment'),
        ),
    ]
