# Generated by Django 2.1.5 on 2020-02-25 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateExpr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('details', models.CharField(max_length=128)),
                ('price', models.IntegerField(default=0)),
                ('start_date', models.DateTimeField(verbose_name='Start date')),
                ('end_date', models.DateTimeField(verbose_name='End date')),
                ('bid_accept', models.BooleanField(default=False)),
                ('num_req', models.IntegerField(default=0)),
                ('num_current', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ExprProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('school', models.CharField(max_length=128)),
                ('webpage', models.CharField(blank=True, max_length=128)),
                ('schoolemail', models.CharField(max_length=128)),
                ('publicnumber', models.CharField(max_length=128)),
                ('isexpr', models.CharField(default=True, max_length=128)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
