# Generated by Django 2.1.5 on 2020-03-22 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experimenter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='details',
            field=models.CharField(max_length=600),
        ),
    ]
