# Generated by Django 2.1.5 on 2020-03-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experimenter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='start_date',
            field=models.DateField(),
        ),
    ]
