# Generated by Django 2.1.5 on 2020-03-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experimenter', '0002_auto_20200322_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='age_req',
            field=models.IntegerField(choices=[(17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, 23), (24, '24'), (25, '25'), (26, '26'), (27, '27'), (28, '28'), (29, '29'), (30, '30')]),
        ),
    ]
