# Generated by Django 2.1.5 on 2020-03-22 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experimenter', '0003_auto_20200322_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='ed_req',
            field=models.CharField(choices=[('School', 'School'), ('College', 'College'), ('Undergraduate', 'Undergraduate'), ('Postgraduate', 'Postgraduate')], max_length=128),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='lang_req',
            field=models.CharField(choices=[('English', 'English'), ('French', 'French'), ('German', 'German'), ('Korean', 'Korean')], max_length=128),
        ),
    ]
