# Generated by Django 2.1.5 on 2020-03-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experimenter', '0005_auto_20200322_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='age_req',
            field=models.IntegerField(choices=[(0, '0'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, 23), (24, '24'), (25, '25'), (26, '26'), (27, '27'), (28, '28'), (29, '29'), (30, '30')], default=0),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='ed_req',
            field=models.CharField(choices=[('None', 'None'), ('School', 'School'), ('College', 'College'), ('Undergraduate', 'Undergraduate'), ('Postgraduate', 'Postgraduate')], max_length=128),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='lang_req',
            field=models.CharField(choices=[('None', 'None'), ('English', 'English'), ('French', 'French'), ('German', 'German'), ('Korean', 'Korean')], max_length=128),
        ),
    ]
