# Generated by Django 2.1.5 on 2020-03-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experimenter', '0006_auto_20200322_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='ed_req',
            field=models.CharField(choices=[(0, 'None'), (1, 'School'), (2, 'College'), (3, 'Undergraduate'), (4, 'Postgraduate')], max_length=128),
        ),
    ]
