# Generated by Django 2.1.5 on 2020-03-22 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experimenter', '0007_auto_20200322_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='ed_req',
            field=models.CharField(choices=[('None', 'None'), ('School', 'School'), ('College', 'College'), ('Undergraduate', 'Undergraduate'), ('Postgraduate', 'Postgraduate')], max_length=128),
        ),
    ]
